apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

components:
  - https://github.com/redhat-na-ssa/demo-ai-gitops-catalog/components/operators/gpu-operator-certified/operator/components/console-plugin?ref=v0.11
